### ISSUE TITLE
PHP 8 incompatibility

### ISSUE THREAD

**Issue by machour** [adserverplugins/apStatsGraphs#2]
Hi,

Here's a fatal error from my logs:

```
PHP message: PHP Fatal error:  Declaration of AP_Graph_Daily::factory($year, $month, $aEntityParams) must be compatible with AP_Graph::factory($aGet)
```

**Comment by mbeccati** [comment]
The plugin is currently unsupported, as it used a Flash-based library to display graphs. No further development is planned atm, sorry.

**Comment by machour** [comment]
Turns out my customer wasn't using it, so it's now disabled. Thank you for getting back to me !
